// <auto-generated />
using System;
using IctTrader.PaperTrading.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IctTrader.PaperTrading.Infrastructure.Migrations
{
    [DbContext(typeof(PaperTradingDbContext))]
    [Migration("20260624132044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IctTrader.Domain.Trading.ArmedEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("ArmedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("armed_at_utc");

                    b.Property<string>("InstrumentClass")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("instrument_class");

                    b.Property<decimal>("PipSize")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("pip_size");

                    b.Property<decimal>("RiskBudget")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("risk_budget");

                    b.Property<string>("Setup")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("setup");

                    b.Property<decimal>("Size")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("size_lots");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValuePerPip")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("value_per_pip");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Status")
                        .HasDatabaseName("ix_armed_entries_account_id_status");

                    b.ToTable("armed_entries", (string)null);
                });

            modelBuilder.Entity("IctTrader.Domain.Trading.PaperAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Equity")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("equity");

                    b.Property<decimal>("MaxOpenPortfolioRiskPercent")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("max_open_portfolio_risk_pct");

                    b.Property<string>("_reservedRiskByTrade")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reserved_risk_by_trade");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("paper_accounts", (string)null);
                });

            modelBuilder.Entity("IctTrader.Domain.Trading.PaperTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("close_reason");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("closed_at_utc");

                    b.Property<decimal?>("Costs")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("costs");

                    b.Property<decimal>("CurrentStop")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("current_stop");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("exit_price");

                    b.Property<decimal?>("GrossPnl")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_pnl");

                    b.Property<bool>("HasScaledOut")
                        .HasColumnType("boolean")
                        .HasColumnName("has_scaled_out");

                    b.Property<decimal>("InitialRiskPerUnit")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("initial_risk_per_unit");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lifecycle");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("opened_at_utc");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("plan");

                    b.Property<decimal?>("RealizedPnl")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("realized_pnl");

                    b.Property<decimal?>("RealizedR")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("realized_r");

                    b.Property<decimal>("RemainingSize")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("remaining_size_lots");

                    b.Property<decimal>("RiskBudget")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("risk_budget");

                    b.Property<decimal>("Size")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("size_lots");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("style");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("timeframe");

                    b.Property<DateTimeOffset>("_lastActivityAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<string>("_legs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("legs");

                    b.Property<decimal>("_pipSize")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("pip_size");

                    b.Property<decimal>("_valuePerPip")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("value_per_pip");

                    b.Property<decimal>("_valuePerPipForPosition")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("value_per_pip_for_position");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ClosedAtUtc")
                        .HasDatabaseName("ix_paper_trades_account_id_closed_at");

                    b.HasIndex("AccountId", "Status")
                        .HasDatabaseName("ix_paper_trades_account_id_status");

                    b.HasIndex("Symbol", "Status")
                        .HasDatabaseName("ix_paper_trades_symbol_status");

                    b.ToTable("paper_trades", (string)null);
                });

            modelBuilder.Entity("IctTrader.Domain.Trading.ArmedEntry", b =>
                {
                    b.HasOne("IctTrader.Domain.Trading.PaperAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IctTrader.Domain.Trading.PaperTrade", b =>
                {
                    b.HasOne("IctTrader.Domain.Trading.PaperAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
