// <auto-generated />
using System;
using IctTrader.MarketData.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IctTrader.MarketData.Infrastructure.Migrations
{
    [DbContext(typeof(MarketDataDbContext))]
    partial class MarketDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IctTrader.MarketData.Infrastructure.Persistence.CandleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("open");

                    b.Property<DateTimeOffset>("OpenTimeUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("open_time_utc");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("timeframe");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Timeframe", "OpenTimeUtc")
                        .IsUnique()
                        .HasDatabaseName("uq_candles_symbol_timeframe_open_time");

                    b.ToTable("candles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
